MODULE WHITENOISE
USE FUNCT
USE MINIMO

CONTAINS
!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!NORMAL DISTRIBUTED RANDOM NUMBERS!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
SUBROUTINE NDRN(N,M,SD,WN)
IMPLICIT NONE
!BOX-MULLER: GIVEN A UNIFORM DISTRIBUTION OF SIZE N, WE DEFINE A NORMAL DISTRIBUTION OF RANDOM NUMBER WITH MEAN M AND STANDARD DEVIATION SD.
REAL*8, PARAMETER:: PI=DACOS(-1D0) 
INTEGER, INTENT(IN):: N
REAL*8, INTENT(IN):: M, SD
REAL*8, INTENT(OUT):: WN(1:N)
INTEGER:: I
REAL*8:: TEMP
CALL RANDOM_NUMBER(WN) ! UNIFORM DISTRIBUTION 
! NOW CONVERT TO NORMAL DISTRIBUTION
DO I = 1, N-1, 2
	TEMP = SD*DSQRT(-2D0*DLOG(WN(I)))*DCOS(2D0*PI*WN(I+1))+M
	WN(I+1) = SD*DSQRT(-2D0*DLOG(WN(I)))*DSIN(2D0*PI*WN(I+1))+M
	WN(I) = TEMP
END DO
END SUBROUTINE NDRN
!!!!!!!!!!!!!!!!!!!!!!!
!!!CONSTRUCTING A NEW SERIE!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
SUBROUTINE TSERIES(T,P,Q,Y,TH,ITER,X)
IMPLICIT NONE
INTEGER, INTENT(IN):: T, P, Q
REAL*8, INTENT(IN):: Y(1:T)
REAL*8, INTENT(INOUT):: TH(1:P+Q+1)
REAL*8, INTENT(OUT):: X(1:T)
INTEGER, INTENT(OUT)::ITER
REAL*8:: ER(1:T), MA, AR, GTOL, FRET
REAL*8:: MED, STD
INTEGER::I, J, K
GTOL=1D-7
ITER=0D0; FRET=0D0
CALL MINDFP(TH,T,P,Q,Y,GTOL,ITER,FRET)
CALL ERRVECT(T,P,Q,Y,TH,ER)
MED=0D0; STD=0D0
DO I=1, T	!3
	MED=MED+ER(I)
ENDDO				!3
MED=MED/DBLE(T)
DO I=1, T	!4
	STD=STD+(ER(I)-MED)**2
END DO 			!4
STD=DSQRT(STD/DBLE(T))
ER=0
CALL NDRN(T,MED,STD,ER) 		
X=0D0
DO I=0,P-1	!1
	X(P-I)=Y(T-I)
END DO 			!1
DO I=P+1,T		!2
	AR=0.D0; MA=0.D0		
	DO J=1 ,P		!2.1
		AR=AR+TH(J)*Y(I-J)
	END DO 			!2.1
	IF (Q .LE. P) THEN
		DO K=1,Q	!2.2
			MA=MA+TH(K+P)*ER(I-K)
		END DO		!2.2
	ELSE
		DO  K=1,P	!2.3
			MA=MA+TH(K+P)*ER(I-K)
		END DO		!2.3
		DO K=P+1,Q	!2.4
			IF (I-K .LT. 1) EXIT
			MA=MA+TH(K+P)*ER(I-K)			
		END DO			!2.4
	END IF
	X(I)=TH(P+Q+1)+ER(I)+AR+MA
END DO 				!2
END SUBROUTINE TSERIES

END MODULE WHITENOISE
